// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RsumeBuilder_Team_9_.Context;

#nullable disable

namespace RsumeBuilder_Team_9_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241120023153_v6")]
    partial class v6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityAndState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("College")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegreeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeInputId")
                        .HasColumnType("int");

                    b.Property<int>("YearGraduated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeInputId");

                    b.ToTable("Degree", (string)null);
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatesWorked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobResponsibilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeInputId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeInputId");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageProficiency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeInputId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResumeInputId");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.ResumeInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ResumeInput", (string)null);
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.Degree", b =>
                {
                    b.HasOne("RsumeBuilder_Team_9_.Models.ResumeInput", null)
                        .WithMany("Degrees")
                        .HasForeignKey("ResumeInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.Job", b =>
                {
                    b.HasOne("RsumeBuilder_Team_9_.Models.ResumeInput", null)
                        .WithMany("Jobs")
                        .HasForeignKey("ResumeInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.Language", b =>
                {
                    b.HasOne("RsumeBuilder_Team_9_.Models.ResumeInput", null)
                        .WithMany("Languages")
                        .HasForeignKey("ResumeInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.ResumeInput", b =>
                {
                    b.HasOne("RsumeBuilder_Team_9_.Models.User", null)
                        .WithOne("ResumeInput")
                        .HasForeignKey("RsumeBuilder_Team_9_.Models.ResumeInput", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.ResumeInput", b =>
                {
                    b.Navigation("Degrees");

                    b.Navigation("Jobs");

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("RsumeBuilder_Team_9_.Models.User", b =>
                {
                    b.Navigation("ResumeInput")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
